name:  Bug Report
description: Reporta un problema o comportamiento inesperado
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: "T铆tulo"
      placeholder: "Describe el problema en una frase"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: " Pasos para reproducir"
      description: "驴C贸mo reproducimos este bug? Explica paso por paso."
      placeholder: |
        1. Ir a '...'
        2. Hacer click en '...'
        3. Observar error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: " Comportamiento esperado"
      placeholder: "Lo que deber铆a haber pasado..."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: " Comportamiento actual"
      placeholder: "Lo que realmente pas贸 (puedes incluir capturas)"
      render: markdown
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: " Versi贸n del m贸dulo afectado"
      placeholder: "p.ej.: preproc v0.1.2"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: " Sistema operativo"
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Otro"
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: "П Entorno"
      description: "Versi贸n de Python, librer铆as, hardware, etc."
      placeholder: "Python 3.10, CUDA 12.2, etc."
      render: markdown

  - type: checkboxes
    id: duplicates
    attributes:
      label: " 驴Buscaste un issue similar?"
      options:
        - label: "S铆, revis茅 y no encontr茅 duplicados"
          required: true

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: " 驴Le铆ste el C贸digo de Conducta?"
      options:
        - label: "S铆, he le铆do el C贸digo de Conducta"
          required: true
